export interface InventarioVehiculosUsados {
    consignacion : string;
    retoma : string;
    otros : string;
    placa : string;
    interno : string;
    asesor : string;
    sala : string;
    fecha : Date;
    hora: Date;
    marca : string;
    referencia : string;
    modelo : string;
    combustible : number;
    kilometraje : number;
    transmision : number;
    color : string;
    cilindraje : number ;
    traccion : string;
    cojineria : string;
    linea : string;
    codigo_estado : string;
    vida_llanta_del_izq : number;
    vida_llanta_del_der : number;
    vida_llanta_tras_izq : number;
    vida_llanta_tras_der : number;
    marca_llanta_del_izq : string;
    marca_llanta_del_der : string;
    marca_llanta_tras_izq : string;
    marca_llanta_tras_der : string;
    observacion_llanta : string;
    rin : string ;
    tapa : string;
    marca_rines_tapa : string;
    observacion_rines : string;
    matricula : number;
    soat : number;
    rtm : number;
    observaciones_documentos : string;
    llaves:  number;
    repuesto_llaves:  number;
    manual : number;
    encendedor : number;
    cruceta : number;
    item_llave : number;
    trinquete_reversible : number;
    gato : number;
    kit_herramientas : number;
    antena : number;
    cubre_maletero : number;
    nivel_gasolina: number;
    marca_bateria : string;
    ref_bateria : string;
    marca_radio: string;
    ref_radio : string;
    observaciones : string;
    nombre_entrega_vehiculo : string;
    fecha_hora_entrega : Date;
    firma_entrega : string;
    empleado_recibe : string;
    nombre_recoge_vehiculo : string;
    fecha_hora_recogida: Date;
    firma_recoge : string;
    empleado_entrega : string;    
}
